apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: adservice
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.observability.svc:14250"
            - name: OTEL_TRACES_EXPORTER
              value: "jaeger"
            - name: OTEL_PROPAGATIONS
              value: "b3"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_INSTRUMENTATION_JDBC_DATASOURCE_ENABLED
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=adservice"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - port: 8095