apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: cartservice
          ports:
          - containerPort: 8091
          env:
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.observability.svc:14250"
            - name: OTEL_TRACES_EXPORTER
              value: "jaeger"
            - name: OTEL_PROPAGATIONS
              value: "b3"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_INSTRUMENTATION_JDBC_DATASOURCE_ENABLED
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=cartservice"                                        
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - port: 8091