apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: checkoutservice
          ports:
          - containerPort: 8090
          env:
            - name: URL_CARTSERVICE
              value: http://cartservice:8091
            - name: URL_PRODUCTSERVICE
              value: http://productservice:8092
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger-collector.observability.svc:14250"
            - name: OTEL_TRACES_EXPORTER
              value: "jaeger"
            - name: OTEL_PROPAGATIONS
              value: "b3"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_INSTRUMENTATION_JDBC_DATASOURCE_ENABLED
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=checkoutservice"                                      
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - port: 8090